Added input data validation by spring annotations
in2workspace/desmos-api pull request #19
Opened 2024-04-09 12:25 UTC by juanmartinin2

2024-04-11 14:45 UTC, oriolcanades requested changes

2024-04-11 14:45 UTC, oriolcanades commented on src/main/java/es/in2/desmos/domain/models/BlockchainNotification.java
> +        @JsonProperty("id") @PositiveOrZero long id,
¿Por qué el id es de tipo long?

2024-04-11 14:45 UTC, oriolcanades commented on src/main/java/es/in2/desmos/domain/models/BlockchainNotification.java
> +        @JsonProperty("timestamp") @PositiveOrZero long timestamp,
¿Podemos buscar cómo añadir una anotación custom que valide el formato? Los Timestamps causan muchos problemas de formato.

2024-04-11 14:45 UTC, oriolcanades commented on src/main/java/es/in2/desmos/domain/models/BlockchainNotification.java
> +        @JsonProperty("relevantMetadata") @NotNull List<@NotBlank String> relevantMetadata,
¿Por qué usamos List<@NotBlankString>? ¿No existe una validación @NotEmpty?

2024-04-11 14:45 UTC, oriolcanades commented on src/main/java/es/in2/desmos/domain/models/BlockchainSubscription.java
> +        @JsonProperty("eventTypes") @NotNull List<@NotBlank String> eventTypes,
Ibidem NotEmpty?

2024-04-11 14:45 UTC, oriolcanades commented on src/main/java/es/in2/desmos/domain/models/BlockchainTxPayload.java
> +        @JsonProperty("relevantMetadata") @NotNull List<@NotBlank String> metadata
Ibidem

2024-04-11 14:45 UTC, oriolcanades commented on src/main/java/es/in2/desmos/domain/models/BrokerNotification.java
> +        @JsonProperty("data") @NotNull List<@NotNull Map<@NotBlank String, Object>> data,
¿Podemos añadir una custom? ¿Hemos validado que esta validación es correcta?

2024-04-12 06:59 UTC, juanmartinin2 commented on src/main/java/es/in2/desmos/domain/models/BlockchainNotification.java
> +        @JsonProperty("id") @PositiveOrZero long id,
Este no es un cambio que yo haya hecho, id es un Long desde la rama "release/v0.6.0-2" de la que se basó mi rama actual, asumo que es Long para anticipar el caso de ids muy largos.

2024-04-12 07:00 UTC, juanmartinin2 commented on src/main/java/es/in2/desmos/domain/models/BlockchainNotification.java
> +        @JsonProperty("timestamp") @PositiveOrZero long timestamp,
Si, la creación de anotaciones de validación custom es posible, intentaré crear una que se adecue con timestamp y la testeare

2024-04-12 07:00 UTC, juanmartinin2 commented on src/main/java/es/in2/desmos/domain/models/BlockchainNotification.java
> +        @JsonProperty("relevantMetadata") @NotNull List<@NotBlank String> relevantMetadata,
Para los campos tipo String la mejor opción es usar @Notblank, ya que hace lo mismo que @NotEmpty, pero agrega la propiedad de que no permite que los espacios en blanco cuenten como una respuesta válida ante un @NotEmpty y cuando es el caso de una lista de strings las anotaciones de validación también pueden aplicarse a los campos de una colección para validar dato por dato

2024-04-12 07:00 UTC, juanmartinin2 commented on src/main/java/es/in2/desmos/domain/models/BrokerNotification.java
> +        @JsonProperty("data") @NotNull List<@NotNull Map<@NotBlank String, Object>> data,
Si es posible crear una validación custom, pero aún debo probar de validar brokerNotifications además de que en este caso al no saber el tipo de dato que será Object no agregue ninguna anotación para el valor del map hasta que pudiera probarlo

2024-04-25 07:12 UTC, oriolcanades requested changes

2024-04-25 07:12 UTC, oriolcanades commented on src/main/java/es/in2/desmos/domain/models/EventQueue.java
> +    private @NotNull(message = "event must not be null") List<Object> event;
No requiere validación

2024-05-02 13:16 UTC, closed without merging